
version: 2.1
jobs:
  test-checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
  test:  
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "test checkout"
          command: |
            echo "verifier la presence du code github"
            ls -l
            wc -l fichier.txt
workflows:
  checkout-test-workflow:
    jobs:
      - checkout
      - test
