
version: 2.1
jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
  test:  
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "test du code"
          command: |
            ls -l
            wc -l fichier
workflows:
  checkout-test-workflow:
    jobs:
      - checkout
      - test
